version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.production
    container_name: app
    environment:
      NODOS_HOST: "0.0.0.0"
      NODOS_PORT: "8080"
    command: ['npm', 'test']
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${NODOS_DB_PASSWORD}
      POSTGRES_USER: ${NODOS_DB_USERNAME}
      POSTGRES_DB: ${NODOS_DB_HOSTNAME}
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
