version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    environment:
      NODOS_HOST: "0.0.0.0"
      NODOS_PORT: "8080"
    volumes:
      - ./:/app
    command: ['npm', 'test']
