version: '3.7'

networks:
  devops-lvl1-network:

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    environment:
      NODOS_HOST: "0.0.0.0"
      NODOS_PORT: "8080"
    networks:
      - devops-lvl1-network
    volumes:
      - ./:/app
    command: ['npm', 'test']
